MyWeb/Controllers/CalendarController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Runtime.ExceptionServices;
using System.Web;
using System.Web.UI.WebControls;
using System.Web.Mvc;
using DayPilot.Web.Mvc;
using DayPilot.Web.Mvc.Enums;
using DayPilot.Web.Mvc.Events.Calendar;
using Microsoft.AspNet.Identity;
using System.Security.Cryptography;
using DayPilot.Web.Mvc.Json;
using DayPilot.Web.Ui;
using JobPortal.Model;


namespace MyWeb.Controllers
{

    public class CalendarController : Controller
    {
        private OfferReference.IOfferService _offerProxy = new OfferReference.OfferServiceClient("OfferServiceHttpEndpoint");
        public ActionResult Backend(int serviceId)
        {
            return new Dpc(serviceId).CallBack(this);
        }



        public ActionResult AddHours(DateTime startT, DateTime endT, int serviceId)
        {

            DayOfWeek wd = startT.DayOfWeek;
            TimeSpan starttime = startT.TimeOfDay;
            TimeSpan endtime = endT.TimeOfDay;
            int serId = serviceId;
            if (_offerProxy.AddHoursToOffer(new WorkingTime { WeekDay = wd,
                Start = starttime, End = endtime, OfferId = serId }))
                return JavaScript(SimpleJsonSerializer.Serialize("Hours are added"));
            return JavaScript(SimpleJsonSerializer.Serialize("You can't add working hours " 
                + starttime + "- " + endtime + "for " + wd));
        }

    }




    class Dpc : DayPilot.Web.Mvc.DayPilotCalendar
    {
        private OfferReference.IOfferService _offerProxy = new OfferReference.OfferServiceClient("OfferServiceHttpEndpoint");
        private int _serviceId;
        public Dpc(int serviceId)
        {
            this._serviceId = serviceId;
        }
        protected override void OnInit(InitArgs e)
        {
            WeekStarts = (WeekStarts)WeekStarts.Parse(typeof(WeekStarts), "" + (int)DateTime.Now.AddDays(7).DayOfWeek);
            UpdateWithMessage("Choose your working hours!", CallBackUpdateType.Full);
        }

        protected override void OnCommand(CommandArgs e)
        {
            switch (e.Command)
            {
                case "refresh":
                    Update();
                    break;
            }
        }

        
        protected override void OnFinish()
        {
            if (UpdateType == CallBackUpdateType.None)
            {
                return;
            }

            DataIdField = "Id";
            DataStartField = "Start";
            DataEndField = "End";
            DataTextField = "Text";

            var days = _offerProxy.GetAllWorkingDays().Where(x => x.OfferId == _serviceId);
            DateTime date = DateTime.Now;
            IList<WorkingDate> list = new List<WorkingDate>();
            foreach (var day in days)
            {
                DateTime startdate = DateTime.Now;
                DateTime enddate = DateTime.Now;

                if (day.WeekDay == DateTime.Now.DayOfWeek)
                {
                    startdate= startdate.Subtract(TimeSpan.FromDays(7)).Date.Add(day.Start);
                    enddate= enddate.AddDays(-7).Date.Add(day.End);
                }
                else if (day.WeekDay == DateTime.Now.AddDays(1).DayOfWeek)
                {
                    startdate = startdate.AddDays(-6).Date.Add(day.Start);
                    enddate  = enddate.AddDays(-6).Date.Add(day.End);

                }
                else if (day.WeekDay == DateTime.Now.AddDays(2).DayOfWeek)
                {
                    startdate = startdate.AddDays(-5).Date.Add(day.Start);
                    enddate  =  enddate.AddDays(-5).Date.Add(day.End);

                }
                else if (day.WeekDay == DateTime.Now.AddDays(3).DayOfWeek)
                {
                    startdate = startdate.AddDays(-4).Date.Add(day.Start);
                    enddate  = enddate.AddDays(-4).Date.Add(day.End);

                }
                else if (day.WeekDay == DateTime.Now.AddDays(4).DayOfWeek)
                {
                    startdate = startdate.AddDays(-3).Date.Add(day.Start);
                    enddate  = enddate.AddDays(-3).Date.Add(day.End);

                }
                else if (day.WeekDay == DateTime.Now.AddDays(5).DayOfWeek)
                {
                    startdate = startdate.AddDays(-2).Date.Add(day.Start);
                    enddate  =  enddate.AddDays(-2).Date.Add(day.End);

                }
                else if (day.WeekDay == DateTime.Now.AddDays(6).DayOfWeek)
                {
                    startdate = startdate.AddDays(-1).Date.Add(day.Start);
                    enddate  =  enddate.AddDays(-1).Date.Add(day.End);

                }

                list.Add(new WorkingDate { Id = day.Id, OfferId = day.OfferId, Text = day.Text, Start = startdate, End = enddate });

                
            }
            Events = list;
        }



    }
}

MyWeb/Controllers/ServiceOfferController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AutoMapper;
using Microsoft.AspNet.Identity;
using System.Threading.Tasks;
using MyWeb.OfferReference;
using PagedList;
using WebJobPortal.Models;
using JobPortal.Model;
using MyWeb.OrderReference;
using MyWeb.UserReference1;

namespace MyWeb.Controllers
{
    public class ServiceOfferController : Controller
    {

        private OfferReference.IOfferService _offerProxy;
        private UserReference1.IUserService _userProxy;
        private OrderReference.IOrderService _orderProxy;
        private IMapper _mapper;
        private IList<WorkingHoursOfOfferModel> workingdays = new List<WorkingHoursOfOfferModel>();


        // GET: Offer

        public ServiceOfferController()
        {
            var config = new MapperConfiguration(cfg =>
            {
                cfg.CreateMap<JobPortal.Model.Offer, ManageOfferModel>();
            });

            _mapper = config.CreateMapper();
            _offerProxy = new OfferReference.OfferServiceClient("OfferServiceHttpEndpoint");
            _orderProxy = new OrderReference.OrderServiceClient("OrderServiceHttpEndpoint");
            _userProxy = new UserReference1.UserServiceClient("UserServiceHttpEndpoint1");


        }
        public ServiceOfferController(IOfferService proxy, IUserService userProxy, IOrderService orderProxy)
        {
            var config = new MapperConfiguration(cfg =>
            {
                cfg.CreateMap<JobPortal.Model.Offer, ManageOfferModel>();
            });
            _mapper = config.CreateMapper();
            _offerProxy = proxy;
            _userProxy = userProxy;
            _orderProxy = orderProxy;
        }

        public ServiceOfferController(IOfferService proxy)
        {
            var config = new MapperConfiguration(cfg =>
            {
                cfg.CreateMap<JobPortal.Model.Offer, ManageOfferModel>();
            });
            _mapper = config.CreateMapper();
            _offerProxy = proxy;
        }
        public async Task<ActionResult> Index(string searchingString, int? page, bool? showInRegion, int? sorting)
        {
            User profile = null;
            var pageIndex = page.HasValue ? Convert.ToInt32(page) : 1;
            var show = showInRegion.HasValue ? Convert.ToBoolean(showInRegion) : false;
            if (User.Identity.IsAuthenticated)
            {
                profile = _userProxy.FindUser(User.Identity.GetUserId());
            }
            var all = await _offerProxy.GetAllOffersAsync();
            IEnumerable<Offer> list = null;
            IPagedList<ManageOfferModel> ipagedList = null;
            switch (sorting)
            {
                case 1://by highet price
                    list = User.Identity.GetUserId() != null && show ?
                all.Where(x => _userProxy.FindUser(x.AuthorId).Region == profile.Region).OrderByDescending(x => x.RatePerHour) :
                all.OrderByDescending(x => x.RatePerHour);
                    break;
                case 2:
                    list = User.Identity.GetUserId() != null && show ?
               all.Where(x => _userProxy.FindUser(x.AuthorId).Region == profile.Region).OrderBy(x => x.RatePerHour) :

               all.OrderBy(x => x.RatePerHour);

                    break;
                case 4://date
                    list = User.Identity.GetUserId() != null && show  ?
                        all.Where(x => _userProxy.FindUser(x.AuthorId).Region == profile.Region):

                    all.Select(x=>x);

                    break;
                case 3:
                    list = User.Identity.GetUserId() != null && show  ?
                        all.Where(x => _userProxy.FindUser(x.AuthorId).Region == profile.Region ).OrderByDescending(x => x.Id):

                    all.OrderByDescending(x => x.Id);

                    break;
                default:
                    list = User.Identity.GetUserId() != null && show ?
                 all.Where(x => _userProxy.FindUser(x.AuthorId).Region == profile.Region).OrderByDescending(x => _offerProxy.GetAvgOfServiceRates(x.Id)
                 as IComparable).ThenBy(x => x.RatePerHour) :

                 all.OrderByDescending(x => _offerProxy.GetAvgOfServiceRates(x.Id) as IComparable).ThenBy(x => x.RatePerHour);
                    break;
            }
            if (searchingString != null)
            {
                ipagedList = list.Where(x => x.Title.ToUpper().Contains(searchingString.ToUpper())).Select(x => _mapper.Map(x, new ManageOfferModel())).ToPagedList(pageIndex, 12);
            }
            else
            {
                ipagedList = list.Select(x => _mapper.Map(x, new ManageOfferModel())).ToPagedList(pageIndex, 12);
            }
            // if (searchingString == null)
            // {
            //     return View("Index", list);
            // }
            //
            // var condition = User.Identity.GetUserId() != null && show ?
            //
            //     all.Where(x => _userProxy.FindUser(x.AuthorId).Region == profile.Region && x.Title.ToUpper().Contains(searchingString.ToUpper())).
            //     OrderByDescending(x => _offerProxy.GetAvgOfServiceRates(x.Id) as IComparable).ThenBy(x => x.RatePerHour).
            //     Select(x => _mapper.Map(x, new ManageOfferModel())).ToPagedList(pageIndex, 12) :
            //
            //     all.Where(x => x.Title.ToUpper().Contains(searchingString.ToUpper())).OrderBy(x => x.RatePerHour).
            //     ThenByDescending(x => _offerProxy.GetAvgOfServiceRates(x.Id) as IComparable).Select(x => _mapper.
            //     Map(x, new ManageOfferModel())).ToPagedList(pageIndex, 12);
            //
            // return View("Index", condition);
            return View("Index", ipagedList);
        }

        public async Task<ActionResult> Home(string searchingString, int? page, bool? showInRegion)
        {
            return await OpenSubcategory(searchingString, page, showInRegion, "Home");
        }

        public async Task<ActionResult> Tutoring(string searchingString, int? page, bool? showInRegion)
        {
            return await OpenSubcategory(searchingString, page, showInRegion, "Tutoring");
        }

        public async Task<ActionResult> IT(string searchingString, int? page, bool? showInRegion)
        {
            return await OpenSubcategory(searchingString, page, showInRegion, "IT");
        }

        public async Task<ActionResult> Repairs(string searchingString, int? page, bool? showInRegion)
        {
            return await OpenSubcategory(searchingString, page, showInRegion, "Repairs");
        }

        public async Task<ActionResult> Architecture(string searchingString, int? page, bool? showInRegion)
        {
            return await OpenSubcategory(searchingString, page, showInRegion, "Architecture");
        }

        public async Task<ActionResult> Media(string searchingString, int? page, bool? showInRegion)
        {
            return await OpenSubcategory(searchingString, page, showInRegion, "Media");
        }

        private async Task<ActionResult> OpenSubcategory(string searchingString, int? page, bool? showInRegion, string subCategoryName)
        {
            User profile = null;
            var pageIndex = page.HasValue ? Convert.ToInt32(page) : 1;
            var show = showInRegion.HasValue ? Convert.ToBoolean(showInRegion) : false;
            if (User.Identity.GetUserId() != null)
            {
                profile = _userProxy.FindUser(User.Identity.GetUserId());
            }
            var all = await _offerProxy.GetAllOffersAsync();

            var list = User.Identity.GetUserId() != null && show ?
                all.Where(x => _userProxy.FindUser(x.AuthorId).Region == profile.Region && x.Category.ToString() == subCategoryName).
                OrderByDescending(x => _offerProxy.GetAvgOfServiceRates(x.Id) as IComparable).ThenBy(x => x.RatePerHour).Select(x =>
                _mapper.Map(x, new ManageOfferModel())).ToPagedList(pageIndex, 12) :

                all.Where(x => x.Category.ToString() == subCategoryName).OrderByDescending(x => _offerProxy.GetAvgOfServiceRates(x.Id)
                as IComparable).ThenBy(x => x.RatePerHour).Select(x => _mapper.Map(x, new ManageOfferModel())).ToPagedList(pageIndex, 12);

            if (searchingString == null)
            {
                return View("Index", list);
            }

            var condition = User.Identity.GetUserId() != null && show ?
                all.Where(x => _userProxy.FindUser(x.AuthorId).Region == profile.Region && x.Title.ToUpper().Contains(searchingString.
                ToUpper()) && x.Category.ToString() == subCategoryName).OrderByDescending(x => _offerProxy.GetAvgOfServiceRates(x.Id) as
                IComparable).ThenBy(x => x.RatePerHour).Select(x => _mapper.Map(x, new ManageOfferModel())).ToPagedList(pageIndex, 12) :

                all.Where(x => x.Title.ToUpper().Contains(searchingString.ToUpper()) && x.Category.ToString() == subCategoryName).
                OrderBy(x => x.RatePerHour).ThenByDescending(x => _offerProxy.GetAvgOfServiceRates(x.Id) as IComparable).
                Select(x => _mapper.Map(x, new ManageOfferModel())).ToPagedList(pageIndex, 12);
            return View("Index", condition);

        }

        public async Task<ActionResult> Add()
        {

            return View("Add", new AddOfferModel());


        }




        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Add(AddOfferModel model)
        {
            bool result = await _offerProxy.CreateServiceOfferAsync(
                Mapping.Mapping.Map_AddServiceOfferModel_To_Offer(model, User.Identity.GetUserId()));
            if (result)
                return RedirectToAction("Index");

            return View("Add", model);


        }

        [HttpGet]

MyWeb/Views/ServiceOffer/Index.cshtml
@model PagedList.IPagedList<ManageOfferModel>
@using PagedList.Mvc;
@using PagedList;
@using WebJobPortal.Models
@using Microsoft.AspNet.Identity;
@{
    ViewBag.Title = "Services";
    Layout = "~/Views/Shared/_Layout.cshtml";
    IList<SelectListItem> selectListItems = new List<SelectListItem>();
    string[] sortlist = { "Highest price", "Lowest price", "Latest", "Oldest", "Best match" };
    int value = 1;
    bool checkedtex = (Request.Url.ToString().Contains("showInRegion=true")) ? true : false;

    foreach (string item in sortlist)
    {
        SelectListItem listItem = new SelectListItem();
        listItem.Text = item;
        listItem.Value = "" + value;
        selectListItems.Add(listItem);
        value++;
    }
}

<div class="row">
    <div class="col-sm-12" style="padding:45px">
        <form>
            <center>
                @Html.TextBox("SearchingString", "", new { id = "searchingstring" })
                <input class="btn btn-light" type="submit" value="Search" id="searchingBar" />
                @if (User.Identity.GetUserId() != null)
                {
                    <div class="form-check">
                        <p>Show in your region  </p>
                        <input type="checkbox" class="form-check-input" id="exampleCheck1" @if (Request.Url.ToString().Contains("showInRegion=true")) { <text> checked</text>} />

                    </div>

                }

            </center>
        </form>
    </div>
</div>
<div>
    <table class="serviceOfferTable" align="center">
        <colgroup>
            <col class="col-md-4">
            <col class="col-md-4">
            <col class="col-md-4">
        </colgroup>
        <tr>
            <td></td>
            <td></td>
            <td style="text-align:right">
                @Html.DropDownList("Sort by", selectListItems, "Sort by", new { id = "sortingList" })
            </td>
        </tr>
        @Html.Partial("Offers", Model)
    </table>
</div>

<script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
<script>
        $('#exampleCheck1').click(function () {

            if ($("#exampleCheck1").is(':checked')) {
                var path = '@Url.Content("~/ServiceOffer/"+ @HttpContext.Current.Request.RequestContext.RouteData.Values["action"].ToString() +"")' + "?showInRegion=true";
                window.location.href = path;
            }
            else {
                var path = '@Url.Content("~/ServiceOffer/"+ @HttpContext.Current.Request.RequestContext.RouteData.Values["action"].ToString() +"")' + "?showInRegion=false";
                window.location.href = path;
            }
    });
    $("#sortingList").click(function () {
        var sortingVal = $(this).val();
        var checked = 'false';
        var searchingString = $("#searchingstring").val();
        console.log("xcvb"+searchingString);
        if ($("#exampleCheck1").is(':checked')) {
            checked = 'true';
        }
        if (searchingString == null) {
            var url = '/ServiceOffer/Index?showInRegion=' + checked + '&sorting=' + sortingVal;
        }
        else
        {
            var url = '/ServiceOffer/Index?SearchingString=' + searchingString + '&showInRegion=' + checked + '&sorting=' + sortingVal;
        }

        location.href = url; // redirect
    });

</script>

MyWeb/Views/ServiceOffer/ViewDetails.cshtml
@model WebJobPortal.Models.ViewDetailsModel
@using WebJobPortal.Models
@using Microsoft.AspNet.Identity;
@using DayPilot.Web.Mvc
@using DayPilot.Web.Mvc.Events.Calendar
@using ViewType = DayPilot.Web.Mvc.Enums.Calendar.ViewType

@{
    ViewBag.Title = Model.Title;
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<link rel="stylesheet" href="http://netdna.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css">

<link href="@Url.Content("~/Content/Rating.css")" rel="stylesheet" type="text/css" />
@Html.Raw(TempData["msg"])


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken() 
    @Html.HiddenFor(model => model.Id)

<div class="offerCard">
    <h2>@Model.Title</h2>

    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="row">
        <div class="col-md-6">
            @if (Model.Category.ToString() == "Home")
            {
                <img class="card-img-top" src="~/Pictures/home.png" alt="Card image" style="width:40%;
                          margin-left:0; margin-right: auto;">
            }
            else if (Model.Category.ToString() == "Tutoring")
            {
                <img class="card-img-top" src="~/Pictures/tutoring.png" alt="Card image" style="width:40%;
                          margin-left:0; margin-right: auto;">
            }
            else if (Model.Category.ToString() == "IT")
            {
                <img class="card-img-top" src="~/Pictures/it.png" alt="Card image" style="width:40%;
                          margin-left:0; margin-right: auto;">
            }
            else if (Model.Category.ToString() == "Repairs")
            {
                <img class="card-img-top" src="~/Pictures/repairs.png" alt="Card image" style="width:40%;
                          margin-left:0; margin-right: auto;">
            }
            else if (Model.Category.ToString() == "Architecture")
            {
                <img class="card-img-top" src="~/Pictures/architecture.png" alt="Card image" style="width:40%;
                          margin-left:0; margin-right: auto;">
            }
            else if (Model.Category.ToString() == "Media")
            {
                <img class="card-img-top" src="~/Pictures/media.png" alt="Card image" style="width:40%;
                          margin-left:0; margin-right: auto;">
            }
        </div>
        <div class="col-md-6">
            @if (Model.Author == User.Identity.GetUserId())
            {
                <div class="form-group">
                    @Html.LabelFor(model => model.Title)

                    <div class="col-md-12" id="edit">
                        @Html.EditorFor(model => model.Title)
                        @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.RatePerHour)

                    <div class="col-md-12" id="edit">
                        @Html.EditorFor(model => model.RatePerHour)
                        @Html.ValidationMessageFor(model => model.RatePerHour, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.Description)

                    <div class="col-md-12" id="edit">
                        @Html.TextAreaFor(model => model.Description, new { style = "width:250px; word-break:break-word;" })
                        @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
                    </div>
                </div>
                <br />
                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Save" class="btn btn-primary" />
                        @Html.ActionLink("Delete", "Delete", "ServiceOffer", new { id = Model .Id }, new { @class = "btn btn-danger" })
                    </div>
                </div>
            }
            else
            {
                <div class="panel panel-default" style="margin-top:20px;">
                    <div class="panel-heading" style="font-size:20px;">@Html.DisplayTextFor(model => model.Title)</div>
                    <div class="panel-body" style="height:130px;">@Html.DisplayTextFor(model => model.Description)</div>
                </div>


                <div class="form-group">
                    @Html.ActionLink("See an author of the service offer", "UserProfile", "User", new { id = Model.Author }, null)
                </div>

            }
        </div>

    </div>
</div>
}
@if (Model.Author != User.Identity.GetUserId())
{<div class="row">
        <div class="col-md-10">
            Available days when you can order the service:
            <div>
                @foreach (var t in Model.Dates.GroupBy(x=>x.WeekDay).Where(x => x.Count() >= 1).Select(y => y.Key))
                {

                    <div>
                        @t.ToString()
                    </div>
                }
            </div>
            <p><span class="glyphicon glyphicon-calendar" style="padding-right:20px;"></span><input type="date" name="days" id="selecteddate"></p>
            <br />
            <p> <span class="glyphicon glyphicon-time" style="padding-right:20px;"></span>@Html.DropDownList("Hours from", new SelectList(""), new { @id = "hoursfrom", @class = "selectlistReview" }) </p>
            <p> <span class="glyphicon glyphicon-time" style="padding-right:20px;"></span> @Html.DropDownList("Hours To", new SelectList(""), new { @id = "hoursto", @class = "selectlistReview" }) </p>
            <br />

            @Html.ActionLink("Add to cart", "AddToCart", "Order", new { serviceID = Model.Id, userID = User.Identity.GetUserId() }, new { @class = "btn btn-info", @id = "addToCart" })
        </div>
    </div>
}



@if (Model.Author == User.Identity.GetUserId())
{

    <br />

    <script src="@Url.Content("~/Scripts/daypilot-all.min.js")" type="text/javascript"></script>

    <div id="dp">
        <br />
        <br />
        <br />


        @Html.DayPilotCalendar("dpc", new DayPilotCalendarConfig
   {
       BackendUrl = Url.Action("Backend", "Calendar",new {serviceId = Model.Id }),
       ViewType = ViewType.Week,
       HeaderDateFormat = "dddd",
       CellDuration = 60,
       Height = 600,
       CellHeight = 30,
       HeightSpec = DayPilot.Web.Mvc.Enums.Calendar.HeightSpec.Full,
       DayBeginsHour= 5,
       DayEndsHour= 22,
       AutoRefreshEnabled = true,
       AutoRefreshInterval = 10,
       DurationBarVisible = true,
       TimeRangeSelectedHandling = TimeRangeSelectedHandlingType.JavaScript,
       TimeRangeSelectedJavaScript = "create(start, end)",
       EventClickHandling = EventClickHandlingType.JavaScript,
       EventDeleteHandling = EventDeleteHandlingType.CallBack,


   })

    </div>

}
else
{
    <div class="row">
        <div class="col-lg-12">
            <h2>Reviews</h2>

            <hr />
        </div>
        <div class="stars">
            <form action="">
                <input class="star star-5" value="5" id="star-5" type="radio" name="star" />
                <label class="star star-5" for="star-5"></label>
                <input class="star star-4" value="4" checked id="star-4" type="radio" name="star" />
                <label class="star star-4" for="star-4"></label>
                <input class="star star-3" value="3" id="star-3" type="radio" name="star" />
                <label class="star star-3" for="star-3"></label>
                <input class="star star-2" value="2" id="star-2" type="radio" name="star" />
                <label class="star star-2" for="star-2"></label>
                <input class="star star-1" value="1" id="star-1" type="radio" name="star" />
                <label class="star star-1" for="star-1"></label>
            </form>
        </div>
        <p hidden id="selectedStar"></p>

        <div class="col-lg-12">
            @Html.TextArea("Your comment", "Your comment", new { style = "max-width: 900px; width:100%;", @id = "commenttxt" })
        </div>
        <div class="col-lg-12">
            @Html.ActionLink("Add review", "AddReview", "ServiceOffer", new { serviceId = Model.Id, customer = User.Identity.GetUserId() }, new { style = "margin-bottom:30px;", @class = "btn btn-danger", @id = "AddReview" })
            <hr />
        </div>
        @if (Model.Reviews != null)
        {
            foreach (ReviewModel review in Model.Reviews)
            {
                @Html.Partial("Review", review)

            }
        }
    </div>

}

<script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>

<script>

    $('#selecteddate').change(function () {
        var selectedDate = $("#selecteddate").val();
        var hourFrom = $('#hoursfrom');
        hourFrom.empty();
        console.log(selectedDate);
        if (selectedDate != null && selectedDate != '') {
            $.getJSON('@Url.Action("GetHoursFrom")', { serviceId: @Model.Id, date: selectedDate }, function (sub) {
                        if (sub != null && !jQuery.isEmptyObject(sub))
                        {
                            console.log(selectedDate);

                            hourFrom.append($('<option/>', {
                                value: null,
                                text: ""
                            }));
                            $.each(sub, function (index, subcats) {
                                console.log(subcats);

                                hourFrom.append($('<option/>', {
                                    value: subcats.Value,
                                    text: subcats.Text
                                }));
                            });
                        };
                    });
                }
            });


    $('#hoursfrom').change(function () {
        var selectedDate = $("#selecteddate").val();
        var selectedHour= $("#hoursfrom").val();
        var hourto = $('#hoursto');

        hourto.empty();
        if (selectedDate != null && selectedDate != '') {

            $.getJSON('@Url.Action("GetHoursTo")', { serviceId: @Model.Id, date: selectedDate, from: selectedHour }, function (sub) {
                console.log("hhhhh");

                        if (sub != null && !jQuery.isEmptyObject(sub))
                        {

                            hourto.append($('<option/>', {
                                value: null,
                                text: ""
                            }));
                            $.each(sub, function (index, subcats) {
                                console.log(subcats.value);
                                hourto.append($('<option/>', {
                                    value: subcats.Value,
                                    text: subcats.Text
                                }));
                            });
                        };
                    });
                }
    });
      $('#addToCart').click(function () {
        var date = $('#selecteddate').val();
        var from = $('#hoursfrom').val();
        var to = $('#hoursto').val();
        var path = '@Url.Content("~/Order/AddToCart")' + "?serviceID=@Model.Id+&userID=@User.Identity.GetUserId()+&date=" + date + "+&from=" + from + "+&to=" + to;
        $(this).attr("href", path);
    });

    $('#AddReview').click(function () {
        var radioValue = $("input[name='star']:checked").val();
        var comment = $('#commenttxt').val();
        var path = '@Url.Content("~/ServiceOffer/AddReview")' + "?serviceId=@Model.Id+&customer=@User.Identity.GetUserId()+&rate=" + radioValue+ "+&comment=" + comment;

        $(this).attr("href", path)

    });



    function create(start, end) {

        var m = new DayPilot.Modal();
        m.closed = function () {
            if (this.result == "Hours are added") {
                dpc.commandCallBack('refresh');
            }

            dpc.clearSelection();
        };
        
              m.showUrl('@Url.Action("AddHours", "Calendar")?startT=' + start + '&endT=' + end + '&serviceId='+@Model.Id );
        
     
    }



</script>